#!/usr/bin/env node
// OSS mission runner — LEAN, practical. Two passes, split at your review gate, so scanning hundreds
// of candidates is fast and the heavyweight Docker receipt is paid ONLY on the fixes you ship.
//
//   PASS 1  SCAN  (default) — recheck (timeline) -> clone at base -> Codex codes in an isolated
//                  clone (filtered env, no host secrets) -> capture diff + PR body. THEN STOP.
//                  No Docker. This is the throughput engine: run it across every candidate.
//   PASS 2  RECEIPT (--receipt) — for each mission you APPROVE after reading its diff: assert the
//                  tree still equals the reviewed commit (head==tested), build the attested receipt
//                  locally (northset-oss run-mission.mjs, Docker), print the exact manual ship.
//
// It never pushes, forks, attests, or opens a PR — that stays the proven manual M-008/M-009 flow,
// printed at the end of the receipt pass.
//
// Usage:
//   node runner.mjs [--only M-010] [--concurrency 4] [--specs <dir>] [--out <dir>] [--replace]  # scan
//   node runner.mjs --receipt [--only M-010] [--specs <dir>] [--out <dir>]                      # ship
//   node runner.mjs --recheck-only [--only M-010]                                               # recheck
// Specs: one JSON per mission in the specs dir (see specs/M-010.example.json). Fields:
//   mission_id, candidate, target_repo, issue_url, base_commit, code_prompt, executor{}, receipt{}
//
// Nothing here is a fortress. It preserves what matters for a solo trusted operator: you review
// every diff and authorize every PR by hand; a timeline recheck guards duplicates. That's it.

import {
  readFile, writeFile, appendFile, mkdir, rm, readdir, stat, symlink, chmod, mkdtemp,
} from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

// ---------------------------------------------------------------- config
const RUNNER_FILE = fileURLToPath(import.meta.url);
const HERE = path.dirname(RUNNER_FILE);
const CFG = {
  northsetOss: '/Users/aeziz-local/northset-oss',
  specsDir: path.join(HERE, 'specs'),
  outDir: path.join(HERE, 'runs'),          // per-mission workdirs + staging receipts
  concurrency: 4,                            // scan has no Docker → raise this to your Codex rate limit
  codexModel: 'gpt-5.6-sol',
  codexEffort: 'xhigh',
  only: null,
  replace: false,
  recheckOnly: false,
  receipt: false,                            // PASS 2: build receipt + ship for already-scanned missions
};

// Codex runs with a throwaway HOME/config. Its parent can read the linked auth file, while commands
// generated by the model receive a filesystem profile that denies host reads outside the clone.
export function codexConfigText() {
  return `approval_policy = "never"
default_permissions = "mission-workspace"
web_search = "disabled"

[history]
persistence = "none"

[features]
apps = false
memories = false
multi_agent = false

[permissions.mission-workspace]
extends = ":workspace"

[permissions.mission-workspace.filesystem]
":root" = "deny"
":minimal" = "read"
":slash_tmp" = "deny"

[permissions.mission-workspace.network]
enabled = false
`;
}

async function createCodexHome() {
  const realHome = process.env.CODEX_HOME ?? path.join(process.env.HOME ?? '', '.codex');
  const auth = path.join(realHome, 'auth.json');
  try {
    await stat(auth);
  } catch {
    throw new Error(`Codex auth file not found at ${auth}`);
  }
  const home = await mkdtemp(path.join(realHome, 'oss-orchestrator-'));
  await chmod(home, 0o700);
  await writeFile(path.join(home, 'config.toml'), codexConfigText(), {mode: 0o600});
  await symlink(auth, path.join(home, 'auth.json'));
  return home;
}

function codexEnv(codexHome, agentHome, tempDir) {
  const allow = ['PATH', 'LANG', 'LC_ALL', 'TERM', 'SHELL', 'USER'];
  const e = {};
  for (const k of allow) if (process.env[k] !== undefined) e[k] = process.env[k];
  e.HOME = agentHome;
  e.TMPDIR = tempDir;
  e.CODEX_HOME = codexHome;
  return e;
}

// ---------------------------------------------------------------- small helpers
export function parseArgs(argv) {
  const o = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--only') o.only = argv[++i];
    else if (a === '--concurrency') o.concurrency = Number(argv[++i]);
    else if (a === '--specs') o.specsDir = argv[++i];
    else if (a === '--out') o.outDir = argv[++i];
    else if (a === '--recheck-only') o.recheckOnly = true;
    else if (a === '--receipt') o.receipt = true;
    else if (a === '--replace') o.replace = true;
    else throw new Error(`unknown arg ${a}`);
  }
  if (o.concurrency !== undefined && (!Number.isInteger(o.concurrency) || o.concurrency < 1)) {
    throw new Error('--concurrency must be a positive integer');
  }
  if (o.receipt && o.recheckOnly) throw new Error('--receipt and --recheck-only are mutually exclusive');
  if (o.receipt && o.replace) throw new Error('--receipt operates on scanned missions; --replace does not apply');
  return o;
}

// Run a command, streaming to a per-mission log file; resolve {code, stdout, stderr}.
function run(cmd, args, { cwd, env, input, logPath, label } = {}) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd, env: env ?? process.env, stdio: ['pipe', 'pipe', 'pipe'] });
    let out = '', err = '';
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { err += d; });
    child.on('close', async (code) => {
      if (logPath) {
        const line = `\n$ ${label ?? `${cmd} ${args.join(' ')}`}\n${out}${err ? `\n[stderr]\n${err}` : ''}\n`;
        await appendFile(logPath, line, {mode: 0o600});
      }
      resolve({ code, stdout: out, stderr: err });
    });
    child.on('error', (e) => resolve({ code: 127, stdout: out, stderr: (err + '\n' + e.message) }));
    if (input !== undefined) { child.stdin.write(input); child.stdin.end(); }
  });
}
function sha256(buf) { return 'sha256:' + createHash('sha256').update(buf).digest('hex'); }

function parseCandidate(value) {
  const m = /^([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)#([1-9][0-9]*)$/.exec(value ?? '');
  if (!m) throw new Error(`invalid candidate ${JSON.stringify(value)}; expected owner/repo#123`);
  return {owner: m[1], repo: m[2], issue: Number(m[3])};
}

function parseGitHubUrl(value, kind) {
  let u;
  try { u = new URL(value); } catch { throw new Error(`${kind} must be an https://github.com URL`); }
  if (u.username || u.password) throw new Error(`${kind} must not contain credentials`);
  if (u.protocol !== 'https:' || u.hostname.toLowerCase() !== 'github.com' || u.port || u.search || u.hash) {
    throw new Error(`${kind} must be an https://github.com URL`);
  }
  const parts = u.pathname.replace(/^\/+|\/+$/g, '').split('/');
  return {parts, url: u};
}

function same(a, b) { return String(a).toLowerCase() === String(b).toLowerCase(); }

function validateSpec(spec) {
  if (!spec || typeof spec !== 'object' || Array.isArray(spec)) throw new Error('mission spec must be an object');
  if (!/^M-[0-9]{3,}$/.test(spec.mission_id ?? '')) {
    throw new Error(`invalid mission_id ${JSON.stringify(spec.mission_id)}; expected M-010`);
  }
  const candidate = parseCandidate(spec.candidate);
  const target = parseGitHubUrl(spec.target_repo, 'target_repo').parts;
  if (target.length !== 2) throw new Error('target_repo must identify exactly one GitHub repository');
  target[1] = target[1].replace(/\.git$/i, '');
  if (!same(target[0], candidate.owner) || !same(target[1], candidate.repo)) {
    throw new Error('target_repo does not match candidate repository');
  }
  const issue = parseGitHubUrl(spec.issue_url, 'issue_url').parts;
  if (issue.length !== 4 || issue[2] !== 'issues' || !/^[1-9][0-9]*$/.test(issue[3])) {
    throw new Error('issue_url must have the form https://github.com/owner/repo/issues/123');
  }
  if (!same(issue[0], candidate.owner) || !same(issue[1], candidate.repo) || Number(issue[3]) !== candidate.issue) {
    throw new Error('issue_url does not match candidate issue');
  }
  if (!/^[0-9a-f]{40}$/i.test(spec.base_commit ?? '')) throw new Error('base_commit must be a full 40-character commit SHA');
  if (typeof spec.code_prompt !== 'string' || spec.code_prompt.trim() === '') throw new Error('code_prompt is required');
  if (!spec.executor || typeof spec.executor !== 'object') throw new Error('executor config is required');
  for (const key of ['install_commands', 'commands']) {
    if (!Array.isArray(spec.executor[key]) || !spec.executor[key].every((x) => typeof x === 'string' && x.trim())) {
      throw new Error(`executor.${key} must be an array of non-empty strings`);
    }
  }
  return spec;
}

export function validateSpecs(specs) {
  const ids = new Set();
  const candidates = new Set();
  for (const spec of specs) {
    validateSpec(spec);
    if (ids.has(spec.mission_id)) throw new Error(`duplicate mission_id ${spec.mission_id}`);
    if (candidates.has(spec.candidate.toLowerCase())) throw new Error(`duplicate candidate ${spec.candidate}`);
    ids.add(spec.mission_id);
    candidates.add(spec.candidate.toLowerCase());
  }
  return specs;
}

export function selectSpecs(specs, only) {
  if (!only) return specs;
  return specs.filter((spec) => spec.mission_id === only);
}

export function safeMissionBase(outDir, missionId) {
  if (!/^M-[0-9]{3,}$/.test(missionId ?? '')) throw new Error(`invalid mission_id ${JSON.stringify(missionId)}`);
  const root = path.resolve(outDir);
  const base = path.resolve(root, missionId);
  if (path.dirname(base) !== root) throw new Error(`mission_id escapes output directory: ${missionId}`);
  return base;
}

async function exists(file) {
  try { await stat(file); return true; } catch (e) { if (e.code === 'ENOENT') return false; throw e; }
}

export async function prepareMissionDir(base, {recheckOnly, replace}) {
  const present = await exists(base);
  if (recheckOnly) {
    await mkdir(base, {recursive: true, mode: 0o700});
    await chmod(base, 0o700);
    return;
  }
  if (present && !replace) throw new Error(`mission directory already exists: ${base}; use --replace to rebuild it`);
  if (present) await rm(base, {recursive: true, force: true});
  await mkdir(base, {recursive: true, mode: 0o700});
  await chmod(base, 0o700);
}
async function ghJson(args) {
  const r = await run('gh', args);
  if (r.code !== 0) throw new Error(`gh ${args.join(' ')} failed: ${r.stderr.trim() || r.stdout.trim()}`);
  return JSON.parse(r.stdout);
}

export function timelineApiArgs(owner, repo, num) {
  return [
    'api', `repos/${owner}/${repo}/issues/${num}/timeline?per_page=100`, '--paginate', '--slurp',
  ];
}

export function timelineCrossReferences(pages) {
  if (!Array.isArray(pages) || !pages.every(Array.isArray)) throw new Error('unexpected paginated timeline response');
  return pages.flat()
    .filter((item) => item?.event === 'cross-referenced' && item?.source?.issue)
    .map((item) => ({
      source: item.source.issue.html_url,
      state: item.source.issue.state,
      title: item.source.issue.title,
      is_pr: item.source.issue.pull_request != null,
    }));
}

// bounded-concurrency pool
async function pool(items, limit, worker) {
  const results = new Array(items.length);
  let next = 0;
  async function lane() {
    while (next < items.length) {
      const i = next++;
      results[i] = await worker(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, lane));
  return results;
}

// ---------------------------------------------------------------- mission steps
// Each step throws on a hard failure; the driver catches and records a status.

async function recheck(spec, log) {
  const {owner, repo, issue: num} = parseCandidate(spec.candidate);
  const issue = await ghJson(['api', `repos/${owner}/${repo}/issues/${num}`,
    '--jq', '{number,state,title,html_url,assignee:.assignee.login,labels:[.labels[].name],created_at,updated_at,body}']);
  // Timeline cross-references: catch prior CLOSED competing PRs (the A-003 lesson), not just open ones.
  // FAIL CLOSED: a failed timeline fetch must NEVER read as "0 competing PRs = clean" (the A-003 trap).
  let timeline;
  try {
    timeline = timelineCrossReferences(await ghJson(timelineApiArgs(owner, repo, num)));
  } catch (e) {
    await log(`recheck: timeline check FAILED — ${e.message} (fail-closed → FAILED)`);
    throw new Error(`timeline recheck failed (fail-closed): ${e.message}`);
  }
  const competingPRs = timeline.filter((t) => t.is_pr);
  const snapshot = { fetched_at: new Date().toISOString().replace(/\.\d+Z$/, 'Z'), issue, comments: [], timeline_cross_references: timeline };
  const reasons = [];
  if (issue.state !== 'open') reasons.push(`issue is ${issue.state}`);
  if (issue.assignee) reasons.push(`assigned to ${issue.assignee}`);
  if (competingPRs.length) reasons.push(`competing PR(s): ${competingPRs.map((p) => `${p.title} [${p.state}]`).join('; ')}`);
  await log(`recheck: state=${issue.state} assignee=${issue.assignee ?? 'none'} crossrefs=${timeline.length} competingPRs=${competingPRs.length}`);
  return { snapshot, clean: reasons.length === 0, reasons };
}

async function prepare(spec, dirs, log) {
  await mkdir(dirs.work, { recursive: true });
  await log(`clone ${spec.target_repo} @ ${spec.base_commit.slice(0, 12)} -> work/`);
  // shallow-friendly: full clone (needed so base_commit + patch provability work), then checkout base.
  let r = await run('git', ['clone', '--no-single-branch', spec.target_repo, dirs.work], { logPath: dirs.log, label: 'git clone' });
  if (r.code !== 0) throw new Error(`clone failed`);
  r = await run('git', ['-C', dirs.work, 'checkout', spec.base_commit], { logPath: dirs.log, label: 'checkout base' });
  if (r.code !== 0) throw new Error(`checkout ${spec.base_commit} failed`);
  await run('git', ['-C', dirs.work, 'switch', '-c', `northset/${spec.mission_id}`], { logPath: dirs.log, label: 'branch' });
}

async function code(spec, dirs, log) {
  const prompt = [
    `You are fixing a real open-source issue. Repository is checked out at the exact base commit ${spec.base_commit}.`,
    ``,
    `Issue: ${spec.issue_url}`,
    ``,
    `Task: ${spec.code_prompt}`,
    ``,
    `Rules: make the MINIMAL focused change that fixes the issue. Follow the repo's existing conventions.`,
    `Add or update tests that fail before and pass after your fix. Update the changelog if the repo requires one.`,
    `Do NOT touch unrelated files. Do NOT change version numbers. When done, ensure the working tree contains only your fix.`,
  ].join('\n');
  await log(`codex coding (${CFG.codexModel} ${CFG.codexEffort}, workspace-only profile)…`);
  const codexHome = await createCodexHome();
  const agentHome = path.join(dirs.work, '.northset-agent-home');
  const tempDir = path.join(dirs.work, '.northset-agent-tmp');
  await Promise.all([
    mkdir(agentHome, {recursive: true, mode: 0o700}),
    mkdir(tempDir, {recursive: true, mode: 0o700}),
  ]);
  let r;
  try {
    r = await run('codex', ['exec',
      '--strict-config',
      '--ephemeral',
      '--ignore-rules',
      '--skip-git-repo-check',
      '--model', CFG.codexModel,
      '-c', `model_reasoning_effort="${CFG.codexEffort}"`,
      '-c', 'service_tier="fast"',
      '--cd', dirs.work,
      '-'],
      {env: codexEnv(codexHome, agentHome, tempDir), input: prompt, logPath: dirs.log, label: 'codex exec'});
  } finally {
    await Promise.all([
      rm(agentHome, {recursive: true, force: true}),
      rm(tempDir, {recursive: true, force: true}),
      rm(codexHome, {recursive: true, force: true}),
    ]);
  }
  if (r.code !== 0) throw new Error(`codex exec failed (see ${path.basename(dirs.log)})`);
  // capture the fix
  await run('git', ['-C', dirs.work, 'add', '-A'], {});
  // "no change needed" is a legitimate outcome (the issue may already be fixed on main — e.g. M-010),
  // not a failure. Distinguish it from a real error so scanning hundreds doesn't drown in false FAILEDs.
  const staged = await run('git', ['-C', dirs.work, 'diff', '--cached', '--name-only']);
  if (!staged.stdout.trim()) { await log(`no change — Codex left the tree unmodified (already fixed?)`); return null; }
  const commit = await run('git', ['-C', dirs.work, 'commit', '-m', `fix: ${spec.candidate}`], { logPath: dirs.log, label: 'commit' });
  if (commit.code !== 0) throw new Error(`git commit failed after a staged change`);
  const shaR = await run('git', ['-C', dirs.work, 'rev-parse', 'HEAD']);
  const patchCommit = shaR.stdout.trim();
  const diffR = await run('git', ['-C', dirs.work, 'diff', `${spec.base_commit}..HEAD`]);
  if (!diffR.stdout.trim()) throw new Error(`empty diff`);
  await writeFile(dirs.patch, diffR.stdout, 'utf8');
  const filesR = await run('git', ['-C', dirs.work, 'diff', '--name-only', `${spec.base_commit}..HEAD`]);
  const changedFiles = filesR.stdout.trim().split('\n').filter(Boolean);
  await log(`patch: ${patchCommit.slice(0, 12)}  (${diffR.stdout.split('\n').length} diff lines, ${changedFiles.length} files)`);
  return {
    baseCommit: spec.base_commit,
    patchCommit,
    patchDiffHash: sha256(Buffer.from(diffR.stdout, 'utf8')),
    changedFiles,
  };
}

async function buildReceipt(spec, dirs, patchInfo, log) {
  // Idempotent: the receipt pass may retry after a flaky Docker phase-A (see M-011). Both dirs are
  // fully derived from work/ + the pipeline, so a clean rebuild is always safe.
  await Promise.all([
    rm(dirs.executorBase, {recursive: true, force: true}),
    rm(dirs.staging, {recursive: true, force: true}),
  ]);
  // Clean base tree for the executor (it applies fix.patch itself).
  await run('git', ['clone', '--local', dirs.work, dirs.executorBase], { logPath: dirs.log, label: 'clone base' });
  await run('git', ['-C', dirs.executorBase, 'checkout', spec.base_commit], { logPath: dirs.log, label: 'base checkout' });
  await rm(path.join(dirs.executorBase, '.git', 'hooks'), { recursive: true, force: true }).catch(() => {});

  const r = spec.receipt ?? {};
  const mission = {
    mission_id: spec.mission_id, variant: 'author_contribution', claims_tier: [], grade: null,
    disclosure_label: 'Northset contributed this fix and ran its declared checks. Contributor self-run. Not maintainer verification.',
    funding_source: 'Northset OSS Fund', northset_role: 'worker_runtime_operator',
    external_counterparty: r.external_counterparty ?? `${spec.candidate.split('/')[0]} maintainers`,
    target_repo: spec.target_repo, issue_or_task: spec.issue_url, consent_artifact: null,
    repo_policy_snapshot: r.repo_policy_snapshot ?? null,
    worker_identity: { runtime: 'northset-oss executor v0', human_operator: 'aeziz' },
    base_commit: spec.base_commit, patch_commit: patchInfo.patchCommit, patch_diff_hash: patchInfo.patchDiffHash,
    commands_declared: spec.executor.commands, environment: null,
    run_record_bundle_digest: null, attestation_uri: null,
    maintainer_outcome: { status: 'pending', link: null, decided_at: null },
    payment: { maintainer_payment: 'none', merge_contingent: false },
    limitations: r.limitations ?? ['Does not prove code quality', 'Does not prove security', 'Contributor self-run record; not maintainer verification.'],
  };
  const input = {
    mission, repo_dir: dirs.executorBase, patch_file: dirs.patch, consent_file: null,
    issue_snapshot_file: dirs.snapshot, ci_links_file: null, executor: spec.executor,
  };
  await writeFile(dirs.input, JSON.stringify(input, null, 2), 'utf8');
  await log(`verify + build receipt (Docker; --require-success)…`);
  const res = await run('node', [path.join(CFG.northsetOss, 'bin', 'run-mission.mjs'),
    dirs.input, '--missions-dir', dirs.staging, '--require-success', '--json'],
    { logPath: dirs.log, label: 'run-mission.mjs' });
  let parsed = null; try { parsed = JSON.parse(res.stdout); } catch { /* leave null */ }
  if (res.code !== 0 || !parsed?.ok) {
    throw new Error(`receipt build failed: ${parsed?.message ?? res.stderr.trim().split('\n').slice(-3).join(' ')}`);
  }
  await log(`receipt OK: ${parsed.missionDir}  bundle ${parsed.bundleDigest}`);
  return parsed;
}

function missionDirs(base) {
  return {
    base, work: path.join(base, 'work'), executorBase: path.join(base, 'executor-base'),
    staging: path.join(base, 'missions'), patch: path.join(base, 'fix.patch'),
    snapshot: path.join(base, 'issue_snapshot.json'), input: path.join(base, 'input.json'),
    prBody: path.join(base, 'pr_body.md'), meta: path.join(base, 'mission.json'),
    log: path.join(base, 'run.log'),
  };
}

function mkLog(spec, dirs) {
  return (m) => appendFile(dirs.log, `[${new Date().toISOString()}] ${m}\n`, {mode: 0o600})
    .then(() => process.stdout.write(`  ${spec.mission_id}  ${m}\n`));
}

// Persisted at scan so the receipt pass can (a) reload the reviewed values and (b) assert the work
// tree still equals the exact commit you reviewed (head==tested) before it builds anything shippable.
function missionMeta(spec, patchInfo) {
  return {
    mission_id: spec.mission_id, candidate: spec.candidate,
    base_commit: patchInfo.baseCommit, patch_commit: patchInfo.patchCommit,
    patch_diff_hash: patchInfo.patchDiffHash, changed_files: patchInfo.changedFiles,
  };
}

// PASS 1 — SCAN. Fast, no Docker. recheck -> clone -> Codex -> diff + PR body -> STOP.
// Terminal states: SKIP (recheck dirty), CLEAN (--recheck-only), NOCHANGE, CODED (ready for review), FAILED.
async function runMission(spec) {
  const base = safeMissionBase(CFG.outDir, spec.mission_id);
  const dirs = missionDirs(base);
  const status = { mission_id: spec.mission_id, candidate: spec.candidate, dirs, state: 'pending', detail: '' };
  const log = mkLog(spec, dirs);
  try {
    await prepareMissionDir(base, {recheckOnly: CFG.recheckOnly, replace: CFG.replace});
    await appendFile(dirs.log, `# ${spec.mission_id} ${spec.candidate}\n`, {mode: 0o600});
    await chmod(dirs.log, 0o600);

    const rc = await recheck(spec, log);
    await writeFile(dirs.snapshot, JSON.stringify(rc.snapshot, null, 2), 'utf8');
    if (!rc.clean) { status.state = 'SKIP'; status.detail = rc.reasons.join('; '); return status; }
    if (CFG.recheckOnly) { status.state = 'CLEAN'; status.detail = 'recheck passed (no code/verify run)'; return status; }

    await prepare(spec, dirs, log);
    const patchInfo = await code(spec, dirs, log);
    if (patchInfo === null) { status.state = 'NOCHANGE'; status.detail = 'Codex left the tree unmodified (already fixed?)'; return status; }
    await writeFile(dirs.meta, JSON.stringify(missionMeta(spec, patchInfo), null, 2), 'utf8');
    await writeFile(dirs.prBody, prBody(spec, patchInfo), 'utf8');  // technical skeleton + MANDATORY receipt footer

    status.state = 'CODED'; status.patchInfo = patchInfo;
    return status;
  } catch (e) {
    status.state = 'FAILED'; status.detail = e.message; return status;
  }
}

// PASS 2 — RECEIPT. Runs ONLY on missions you already scanned and approved. Builds the attested
// receipt (Docker) and prints the manual ship. Terminal states: READY, SKIP (recheck dirty at ship), FAILED.
async function receiptMission(spec) {
  const base = safeMissionBase(CFG.outDir, spec.mission_id);
  const dirs = missionDirs(base);
  const status = { mission_id: spec.mission_id, candidate: spec.candidate, dirs, state: 'pending', detail: '' };
  const log = mkLog(spec, dirs);
  try {
    if (!await exists(dirs.meta)) throw new Error(`no scanned mission at ${base} — run the scan pass first`);
    const meta = JSON.parse(await readFile(dirs.meta, 'utf8'));
    // head==tested: refuse to ship a tree that drifted from the exact commit you reviewed.
    const head = (await run('git', ['-C', dirs.work, 'rev-parse', 'HEAD'])).stdout.trim();
    if (head !== meta.patch_commit) {
      throw new Error(`work tree drifted: HEAD ${head.slice(0, 12)} != reviewed ${meta.patch_commit.slice(0, 12)}`);
    }
    // Recheck again at ship time — the issue may have been closed/assigned/duplicated while it waited
    // in your review queue. Fail-closed (recheck itself throws on a failed timeline fetch — A-003).
    const rc = await recheck(spec, log);
    await writeFile(dirs.snapshot, JSON.stringify(rc.snapshot, null, 2), 'utf8');
    if (!rc.clean) { status.state = 'SKIP'; status.detail = `recheck at ship: ${rc.reasons.join('; ')}`; return status; }

    const patchInfo = {
      baseCommit: meta.base_commit, patchCommit: meta.patch_commit,
      patchDiffHash: meta.patch_diff_hash, changedFiles: meta.changed_files,
    };
    const receipt = await buildReceipt(spec, dirs, patchInfo, log);
    await writeFile(dirs.prBody, prBody(spec, patchInfo), 'utf8');  // refresh; footer guaranteed present

    status.state = 'READY'; status.patchInfo = patchInfo; status.receipt = receipt;
    return status;
  } catch (e) {
    status.state = 'FAILED'; status.detail = e.message; return status;
  }
}

// ---------------------------------------------------------------- PR body
// MANDATORY on every OSS PR: the Northset receipt-disclosure footer. It is the visibility
// mechanism — reviewers follow the link, verify reproducibility, and discover Northset. NEVER omit
// it (dropping it is why M-011 had to be fixed by hand). Modeled on M-007/008/009. See the
// feedback_oss_pr_standard_technical memory. This constant is the single enforcement point.
export const RECEIPT_FOOTER = [
  '---',
  'Disclosure: this change was prepared with AI assistance and reviewed by me before submitting.',
  'I ran the check(s) above in a network-isolated container and published a signed, re-runnable',
  'record of that run, verifiable via GitHub artifact attestation:',
  'https://northset-oss.github.io/verification-pilot/. Contributor self-run, not a maintainer verification.',
].join('\n');

// Generates a PR-body TEMPLATE: a technical skeleton (Summary/Change/Checks/Fixes) plus the
// mandatory RECEIPT_FOOTER. The owner refines the Summary/Change prose before opening the PR; the
// footer is guaranteed present so it can never be forgotten.
export function prBody(spec, patchInfo) {
  const num = parseCandidate(spec.candidate).issue;
  const files = (patchInfo.changedFiles ?? []).map((f) => `- \`${f}\``).join('\n') || '- (see fix.patch)';
  const checks = spec.executor.commands.map((c) => `- \`${c}\` — passed in a network-isolated container.`).join('\n');
  return [
    `<!-- PR title — edit to a clear, conventional summary (e.g. "fix(...): ...") before opening. -->`,
    ``,
    `## Summary`,
    ``,
    `<!-- 2–4 sentences: the problem and your fix. Issue: ${spec.issue_url} -->`,
    ``,
    `## Change`,
    ``,
    files,
    ``,
    `### Checks`,
    checks,
    ``,
    `Fixes #${num}`,
    ``,
    RECEIPT_FOOTER,
    ``,
  ].join('\n');
}

// ---------------------------------------------------------------- report
function board(results) {
  const w = (s, n) => String(s).padEnd(n);
  console.log('\n' + '='.repeat(78) + '\nMISSION RUN — REVIEW BOARD\n' + '='.repeat(78));
  for (const r of results) {
    const mark = { READY: '✓ READY ', CODED: '✎ CODED ', CLEAN: '✓ CLEAN ', NOCHANGE: '· NOCHG ', SKIP: '– SKIP  ', FAILED: '✗ FAILED' }[r.state] ?? r.state;
    console.log(`${mark}  ${w(r.mission_id, 8)} ${r.candidate}`);
    if (['SKIP', 'FAILED', 'CLEAN', 'NOCHANGE'].includes(r.state)) console.log(`           ${r.detail}`);
    if (r.state === 'CODED') {
      console.log(`           diff:    ${r.dirs.patch}   (${(r.patchInfo?.changedFiles ?? []).length} files)`);
      console.log(`           pr body: ${r.dirs.prBody}   (receipt footer INCLUDED — refine Summary/Change)`);
      console.log(`           log:     ${r.dirs.log}`);
    }
    if (r.state === 'READY') {
      console.log(`           diff:    ${r.dirs.patch}`);
      console.log(`           pr body: ${r.dirs.prBody}   (receipt footer INCLUDED — refine Summary/Change)`);
      console.log(`           receipt: ${r.receipt.missionDir}   bundle ${r.receipt.bundleDigest}`);
      console.log(`           log:     ${r.dirs.log}`);
    }
  }
  const coded = results.filter((r) => r.state === 'CODED');
  const ready = results.filter((r) => r.state === 'READY');
  if (coded.length) {
    console.log('\n' + '-'.repeat(78) + '\nNEXT — review each diff, then build receipts only for the ones you approve:\n' + '-'.repeat(78));
    for (const line of scanNextStepLines(coded, CFG)) console.log(line);
  }
  if (ready.length) {
    console.log('\n' + '-'.repeat(78) + '\nNEXT — your human gate, then the proven manual ship:\n' + '-'.repeat(78));
    console.log(`1. REVIEW each READY diff above (read every line).`);
    console.log(`2. For each you AUTHORIZE, run the proven manual ship (unchanged M-008/M-009 flow):`);
    for (const r of ready) {
      console.log(`\n   # ${r.mission_id} (${r.candidate})`);
      for (const line of manualShipLines(r, CFG)) console.log(`   ${line}`);
    }
  }
  console.log('\n(The runner never pushes/forks/attests/PRs. Those stay your manual, reviewed steps.)\n');
}

function shellQuote(value) { return `'${String(value).replaceAll("'", "'\\''")}'`; }

// The exact PASS-2 command for one approved mission. Per-mission by design: you authorize THAT diff.
export function receiptCommand(missionId, options = CFG) {
  const runner = shellQuote(RUNNER_FILE);
  return `node ${runner} --specs ${shellQuote(options.specsDir)} --out ${shellQuote(options.outDir)} --receipt --only ${shellQuote(missionId)}`;
}

export function scanNextStepLines(coded, options = CFG) {
  const lines = [
    `1. REVIEW each CODED diff above (read every line — this is the gate volume never buys down).`,
    `2. For each you AUTHORIZE, build its receipt and get the exact manual ship commands:`,
  ];
  for (const r of coded) lines.push(`   ${receiptCommand(r.mission_id, options)}   # ${r.candidate}`);
  return lines;
}

export function manualShipLines(r, options = CFG) {
  const commit = r.patchInfo.patchCommit;
  const branch = `northset/${r.mission_id}`;
  const repo = parseCandidate(r.candidate).repo;
  const runner = shellQuote(RUNNER_FILE);
  const work = shellQuote(r.dirs.work);
  const recheck = `node ${runner} --specs ${shellQuote(options.specsDir)} --out ${shellQuote(options.outDir)} --only ${shellQuote(r.mission_id)} --recheck-only`;
  return [
    `# base_commit: ${r.patchInfo.baseCommit ?? '(see spec)'}`,
    `# reviewed commit: ${commit}`,
    `# patch_diff_hash: ${r.patchInfo.patchDiffHash}`,
    `# receipt_bundle_digest: ${r.receipt.bundleDigest}`,
    recheck,
    `test "$(git -C ${work} rev-parse HEAD)" = ${shellQuote(commit)}`,
    `git -C ${work} remote get-url fork >/dev/null 2>&1 || git -C ${work} remote add fork ${shellQuote(`https://github.com/AysajanE/${repo}.git`)}`,
    `# Copy the receipt into northset-oss, commit exactly one mission, push, and verify attestation.`,
    `git -C ${work} push fork ${commit}:refs/heads/${branch}`,
    `# Immediately before opening the PR, recheck again:`,
    recheck,
    `# Open the PR — body is pre-generated WITH the mandatory Northset receipt footer; refine the`,
    `# title + Summary/Change first, then:`,
    `#   gh pr create --repo <owner>/${repo} --base <default-branch> --head AysajanE:${branch} --title '<edit>' --body-file ${shellQuote(r.dirs.prBody)}`,
    `# Then assert the opened PR head OID equals ${commit}.`,
  ];
}

export function resultExitCode(results, {recheckOnly = false} = {}) {
  if (results.some((r) => r.state === 'FAILED')) return 1;
  if (recheckOnly && results.some((r) => r.state !== 'CLEAN')) return 1;
  return 0;
}

// ---------------------------------------------------------------- main
async function main() {
  Object.assign(CFG, parseArgs(process.argv.slice(2)));
  const files = (await readdir(CFG.specsDir).catch(() => []))
    .filter((f) => f.endsWith('.json') && !f.includes('.example.'));
  if (!files.length) { console.error(`no mission specs in ${CFG.specsDir}`); process.exit(1); }
  const loaded = [];
  for (const f of files) loaded.push(JSON.parse(await readFile(path.join(CFG.specsDir, f), 'utf8')));
  const specs = selectSpecs(loaded, CFG.only);
  if (!specs.length) { console.error(`no mission spec with mission_id ${CFG.only} in ${CFG.specsDir}`); process.exit(1); }
  validateSpecs(specs);
  const pass = CFG.receipt ? 'RECEIPT (build + ship)' : CFG.recheckOnly ? 'RECHECK' : 'SCAN (code + review)';
  const worker = CFG.receipt ? receiptMission : runMission;
  console.log(`Pass: ${pass} — ${specs.length} mission(s), ${CFG.concurrency} at a time: ${specs.map((s) => s.mission_id).join(', ')}\n`);
  const results = await pool(specs, CFG.concurrency, worker);
  board(results);
  process.exitCode = resultExitCode(results, {recheckOnly: CFG.recheckOnly});
}

if (process.argv[1] && path.resolve(process.argv[1]) === RUNNER_FILE) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
